- name: Make sure snapd is installed
  package:
    name:
      - snapd
    state: latest
  become: yes
  when: ansible_distribution != 'Archlinux'

- name: Make sure snapd is installed
  pacman:
    name:
      - snapd
    state: present
  become: yes
  when: ansible_distribution == 'Archlinux'

- name: Install microk8s
  become: yes
  snap:
    name: microk8s
    classic: yes
    channel: "{{ microk8s_version }}"

- name: Wait for microk8s to be ready
  become: yes
  command: microk8s.status --wait-ready
  changed_when: false
  register: mk8sstatusout
  failed_when:
      - "'This MicroK8s deployment is acting as a node in a cluster.' not in mk8sstatusout.stdout_lines"
      - mk8sstatusout.rc > 0

- name: Add ubuntu user to microk8s group
  user:
    name: "{{ ansible_ssh_user }}"
    groups: microk8s
    append: yes

- name: Create kubectl alias
  become: yes
  command: "snap alias microk8s.kubectl kubectl"
  changed_when: false
  register: aliaskubectlout

- name: Create helm3 alias
  become: yes
  command: "snap alias microk8s.helm3 helm"
  changed_when: false
  register: aliashelmout

- name: Enable microk8s addons
  shell: |
        microk8s enable dns:1.1.1.1 storage ingress metrics-server

- name: custom cert server.key 10 years
  become: yes
  command: "/snap/microk8s/current/usr/bin/openssl req -new -sha256 -key /var/snap/microk8s/current/certs/server.key -out /var/snap/microk8s/current/certs/server.csr -config /var/snap/microk8s/current/certs/csr.conf"

- name: custom cert server.csr 10 years
  become: yes
  command: "/snap/microk8s/current/usr/bin/openssl x509 -req -sha256 -in /var/snap/microk8s/current/certs/server.csr -CA /var/snap/microk8s/current/certs/ca.crt -CAkey /var/snap/microk8s/current/certs/ca.key -CAcreateserial -out /var/snap/microk8s/current/certs/server.crt -days 3650 -extensions v3_ext -extfile /var/snap/microk8s/current/certs/csr.conf"

- name: custom cert front-proxy-client.csr 10 years
  become: yes
  command: "/snap/microk8s/current/usr/bin/openssl x509 -req -sha256 -in /var/snap/microk8s/current/certs/front-proxy-client.csr -CA /var/snap/microk8s/current/certs/front-proxy-ca.crt -CAkey /var/snap/microk8s/current/certs/front-proxy-ca.key -CAcreateserial -out /var/snap/microk8s/current/certs/front-proxy-client.crt -days 3650 -extensions v3_ext -extfile /var/snap/microk8s/current/certs/csr.conf"

- name: Disable snap autoupdate
  become: yes
  command: "snap refresh --hold=forever"

- name: Reboot a slow machine that might have lots of updates to apply
  ansible.builtin.reboot:
    reboot_timeout: 360